language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - TRAVIS_NODE_VERSION="12"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g codecov
  - npm install
  - pip install --upgrade pytest pytest-cov codecov flake8 virtualenv urllib3[secure]
  - pip install -r requirements.txt

script:
  - export CODECOV_TOKEN="89d22de7-bfaf-43a0-81da-33cc733fd294"
  - npm test
  - npm run lint
  - npm run pytest
  - npm run pylint
  - which -a codecov | bash
